import React,{useState,useEffect} from 'react';
import {Card} from './ui/Card';import {Button} from './ui/Button';import {useTheme} from '../contexts/ThemeContext';import {cn} from '../utils/helpers';
const base=(import.meta as any).env?.DEV?'https://ttecrm.vercel.app':'';
export default function MaxAutomationSettings(){
 const {getTextColor,getInputClass}=useTheme();const [loaded,setLoaded]=useState(false),[enabled,setEnabled]=useState(false),[url,setUrl]=useState(''),[secret,setSecret]=useState(''),[configured,setConfigured]=useState(false),[deliveries,setDeliveries]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function load(){try{const r=await fetch(base+'/api/max-settings',{headers:{Authorization:'Bearer '+localStorage.getItem('tte_token')}}),j=await r.json();if(!r.ok)throw Error(j.error?.message||'Settings unavailable.');setEnabled(j.data.enabled);setUrl(j.data.target_url||'');setConfigured(j.data.secret_configured);setDeliveries(j.deliveries||[]);setLoaded(true);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{const r=await fetch(base+'/api/max-settings',{method:'POST',headers:{Authorization:'Bearer '+localStorage.getItem('tte_token'),'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({enabled,...(url.trim()?{target_url:url.trim()}:{}),...(secret?{signing_secret:secret}:{})})}),j=await r.json();if(!r.ok)throw Error(j.error?.message||'Settings could not be saved.');setSecret('');await load();setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Card className="space-y-4"><div><h2 className={cn('text-base font-semibold',getTextColor())}>MAX sales automation</h2><p className="text-sm opacity-60 mt-1">Signed events for admin and unassigned leads. CRM schedules follow-ups; MAX sends the customer messages.</p></div>{!loaded&&!error?<p role="status">Loading settings…</p>:<form onSubmit={save} className="space-y-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)} disabled={busy} className="focus-visible:ring-2"/> Enable outbound events</label><div className="grid md:grid-cols-2 gap-4"><label className="text-sm space-y-1 block">MAX webhook URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-bot.example/webhook" className={cn('w-full focus-visible:ring-2',getInputClass())} required={enabled}/></label><label className="text-sm space-y-1 block">Signing secret<input type="password" value={secret} autoComplete="new-password" onChange={e=>setSecret(e.target.value)} minLength={32} maxLength={256} placeholder={configured?'Saved — leave blank to keep':'At least 32 characters'} className={cn('w-full focus-visible:ring-2',getInputClass())} required={enabled&&!configured}/></label></div><p className="text-xs opacity-60">Follow-ups: 3 hours · tomorrow 10:30 AM · day 2 at 6 PM · day 4 at 11 AM IST. Replies, closed leads and transfer to another team member cancel pending steps.</p><Button type="submit" disabled={busy}>{busy?'Saving…':'Save MAX settings'}</Button></form>}{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}{saved&&<p role="status" className="text-sm">MAX settings saved.</p>}{deliveries.length>0&&<div className="overflow-x-auto"><table className="w-full text-sm text-left"><caption className="text-left font-medium mb-2">Recent deliveries</caption><thead><tr><th className="p-2">Event</th><th className="p-2">State</th><th className="p-2">Attempts</th><th className="p-2">HTTP</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id} className="border-t border-current/10"><td className="p-2">{d.event}</td><td className="p-2">{d.state}</td><td className="p-2">{d.attempts}</td><td className="p-2">{d.last_http_status||'—'}</td></tr>)}</tbody></table></div>}</Card>;
}
