import { build } from 'esbuild';
// Commit the handler and rebuild it on every deploy so Git deployments retain the API.
await build({entryPoints:['lib/botApiProduction.ts'],bundle:true,platform:'node',format:'esm',packages:'external',outfile:'api/bot.js',banner:{js:'// Generated by scripts/build-bot-api.mjs. Do not edit directly.'}});

for (const [entry,out] of [['lib/maxSettings.ts','api/max-settings.js'],['lib/maxWorker.ts','api/max-worker.js']]) await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',packages:'external',outfile:out,banner:{js:'// Generated by scripts/build-bot-api.mjs. Do not edit directly.'}});
