import { build } from 'esbuild';
// Commit the handler and rebuild it on every deploy so Git deployments retain the API.
await build({entryPoints:['lib/botApiProduction.ts'],bundle:true,platform:'node',format:'esm',packages:'external',outfile:'api/bot.js',banner:{js:'// Generated by scripts/build-bot-api.mjs. Do not edit directly.'}});
