import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {hotels,packages,itineraryQuote,rannQuote} from '../lib/botItinerary';
import {createRannQuotationPdf} from '../services/rannQuotationPdf';
import {quoteStay} from '../services/rajarshiRates';
import {RAJARSHI_HOTELS} from '../services/rajarshiData';
const input={check_in:'2026-11-15',nights:2,rooms:1,category:'Premium Tent',extra_mattresses:0,discount_percent:5,guest_name:'API Verification Guest'};
assert.throws(()=>rannQuote({...input,check_in:'2026-02-30'}));
assert.throws(()=>rannQuote({...input,rooms:0}));
assert.throws(()=>rannQuote({...input,check_in:'2027-03-07',nights:2}));
assert.equal(rannQuote(input).data.price.total,41701);
const h=RAJARSHI_HOTELS[0];
const q=itineraryQuote({product:'rajarshi',hotel_id:h.id,room_index:0,plan:'CPAI',check_in:'2026-11-18',nights:2,rooms:1,markup_value:10});
assert.equal(q.total,quoteStay({hotel:h,room:h.rooms[0],plan:'CPAI',checkIn:'2026-11-18',nights:2,rooms:1,extraPersons:0,markupMode:'percent',markupValue:10}).sellingPrice);
const blocked=itineraryQuote({product:'rajarshi',hotel_id:h.id,room_index:0,plan:'CPAI',check_in:'2026-11-08',nights:1,rooms:1});
assert.equal(blocked.quotable,false);assert.equal(blocked.total,null);
assert.ok(hotels({supplier:'inland'}).length>0);assert.equal(packages({}).length,5);
assert.throws(()=>itineraryQuote({product:'inland',hotel_id:hotels({supplier:'inland'})[0].id,room_index:0,check_in:'2026-11-15',nights:1,rooms:1}));
const pdf=await createRannQuotationPdf(rannQuote(input).model,async name=>(await fs.readFile('public/quotation-assets/'+name)).toString('base64'));
await fs.mkdir('output/pdf',{recursive:true});await fs.writeFile('output/pdf/rann-api-verification.pdf',Buffer.from(pdf.output('arraybuffer')));
console.log('Validation and rate parity checks passed. PDF pages:',pdf.getNumberOfPages());
