// Generated by scripts/build-bot-api.mjs. Do not edit directly.

// lib/maxWorker.ts
import crypto2 from "node:crypto";

// lib/maxServerDb.ts
async function maxDb(path, init = {}) {
  const url = process.env.SUPABASE_URL, key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw Error("MAX database is not configured.");
  const r = await fetch(url + "/rest/v1/" + path, { ...init, headers: { apikey: key, Authorization: "Bearer " + key, "Content-Type": "application/json", ...init.headers || {} }, signal: AbortSignal.timeout(2e4) });
  const value = await r.json().catch(() => null);
  if (!r.ok) throw Error("MAX database request failed: " + (value?.code || r.status));
  return value;
}

// lib/maxAutomation.ts
import crypto from "node:crypto";
import dns from "node:dns/promises";
import net from "node:net";
import https from "node:https";
var MaxInputError = class extends Error {
  constructor() {
    super(...arguments);
    this.status = 400;
    this.code = "invalid_request";
  }
};
var bad = (s) => {
  throw new MaxInputError(s);
};
function privateAddress(address) {
  if (net.isIP(address) === 4) {
    const [a2, b] = address.split(".").map(Number);
    return a2 === 0 || a2 === 10 || a2 === 127 || a2 >= 224 || a2 === 169 && b === 254 || a2 === 172 && b >= 16 && b <= 31 || a2 === 192 && b === 168 || a2 === 100 && b >= 64 && b <= 127 || a2 === 198 && (b === 18 || b === 19);
  }
  const a = address.toLowerCase();
  return a === "::" || a === "::1" || a.startsWith("fc") || a.startsWith("fd") || a.startsWith("fe80") || a.startsWith("ff") || a.startsWith("::ffff:");
}
async function validateTarget(value) {
  let u;
  try {
    u = new URL(value);
  } catch {
    bad("target_url must be a public HTTPS URL.");
  }
  if (u.protocol !== "https:" || u.username || u.password || u.hash || u.port && u.port !== "443" || u.hostname === "localhost" || u.hostname.endsWith(".local") || u.href.length > 2e3) bad("target_url must be a public HTTPS URL without credentials.");
  let addresses;
  try {
    addresses = await dns.lookup(u.hostname, { all: true });
  } catch {
    bad("Webhook hostname could not be resolved.");
  }
  if (!addresses.length || addresses.some((a) => privateAddress(a.address))) bad("Webhook target cannot resolve to a private network.");
  return u.href;
}
function signWebhook(raw, secret, timestamp) {
  return `t=${timestamp},v1=${crypto.createHmac("sha256", secret).update(`${timestamp}.${raw}`).digest("hex")}`;
}
var safeWebhookRequest = async (input, init = {}) => {
  const url = new URL(String(input));
  return await new Promise((resolve, reject) => {
    const req = https.request(url, { method: "POST", headers: init.headers, signal: init.signal, lookup: ((hostname, options, callback) => {
      dns.lookup(hostname, { all: true }).then((addresses) => {
        if (!addresses.length || addresses.some((a) => privateAddress(a.address))) return callback(Error("Private webhook target"));
        const first = addresses[0];
        if (options?.all) callback(null, [first]);
        else callback(null, first.address, first.family);
      }).catch(callback);
    }) }, (response) => {
      response.destroy();
      resolve(new Response(null, { status: response.statusCode || 500 }));
    });
    req.on("error", reject);
    req.end(init.body);
  });
};
async function dispatchWebhooks(db, request = safeWebhookRequest) {
  const jobs = await db("rpc/crm_max_claim", { method: "POST", body: JSON.stringify({ p_limit: 20 }) });
  let delivered = 0, failed = 0, skipped = 0;
  await Promise.all((jobs || []).map(async (job) => {
    const event = await db("rpc/crm_max_preflight", { method: "POST", body: JSON.stringify({ p_id: job.id, p_lease: job.lease_token }) });
    if (!event) {
      skipped++;
      return;
    }
    let status = 0, error = "";
    try {
      const target = await validateTarget(event.target_url), raw = JSON.stringify(event.body), timestamp = Math.floor(Date.now() / 1e3);
      const response = await request(target, { method: "POST", body: raw, headers: { "Content-Type": "application/json", "X-MAX-Signature": signWebhook(raw, event.signing_secret, timestamp), "X-MAX-Event-Id": job.id, "X-MAX-Event": job.event, ...process.env.MAX_WEBHOOK_AUTHORIZATION && target === process.env.MAX_WEBHOOK_AUTH_TARGET_URL ? { Authorization: process.env.MAX_WEBHOOK_AUTHORIZATION } : {} }, redirect: "error", signal: AbortSignal.timeout(1e4) });
      status = response.status;
      if (response.body) await response.body.cancel();
      if (status < 200 || status >= 300) error = `Receiver returned HTTP ${status}`;
    } catch (e) {
      error = e instanceof MaxInputError ? e.message : "Webhook network request failed or timed out";
    }
    await db("rpc/crm_max_finish", { method: "POST", body: JSON.stringify({ p_id: job.id, p_lease: job.lease_token, p_status: status, p_error: error }) });
    if (status >= 200 && status < 300) delivered++;
    else failed++;
  }));
  return { claimed: (jobs || []).length, delivered, failed, skipped };
}

// lib/maxWorker.ts
async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  if (req.method !== "GET") return res.status(405).json({ error: { code: "method_not_allowed" } });
  const secret = process.env.CRON_SECRET || "", given = String(req.headers?.authorization || "");
  const expected = "Bearer " + secret;
  if (!secret || given.length !== expected.length || !crypto2.timingSafeEqual(Buffer.from(given), Buffer.from(expected))) return res.status(401).json({ error: { code: "unauthorized" } });
  try {
    return res.status(200).json(await dispatchWebhooks(maxDb));
  } catch {
    return res.status(503).json({ error: { code: "worker_unavailable", message: "MAX queue could not be processed." } });
  }
}
export {
  handler as default
};
